version: "3.7"

services:
  pg_db:
    image: postgres:12
    container_name: pg12
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=bot
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    #ports:
    #  - 5432:5432

  bot:
    build: bot/
    command:
      - dotnet SantaBot.dll
    ports:
      - 8080:80
    #network_mode: bridge
    volumes:
      - ./bot_data:/wwwroot/
    depends_on:
      - pg_db
